<?php
/**
 * Override cookiebanner template html
 * @param string $html
 *
 * @return string
 */

function cmplz_custom_banner_file($path, $filename){
  if ($filename === 'cookiebanner.php' ) {
	error_log("change path to ".trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner/cookiebanner.php');
	return trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner/cookiebanner.php';
  }
  return $path;
}

add_filter('cmplz_template_file', 'cmplz_custom_banner_file', 10, 2);

/**
 * Completely override CSS generated by Complianz
 * @param string $css
 *
 * @return string
 */

function my_custom_banner_css($css){
	ob_start();
	//add css below
	?>
	.cmplz-cookiebanner {

	}
	<?php
	return ob_get_clean();
}
add_filter('cmplz_cookiebanner_css', 'my_custom_banner_css');